all:
  hosts:
    mail.example.com:
  children:
    webservers:
      hosts:
        foo.example.com:
          http_port: 80
          maxRequestsPerChild: 808
        bar.example.com:
          http_port: 303
          maxRequestsPerChild: 909
      vars:
        health_check: "/status?r=health"    
    dbservers:
      hosts:
        one.example.com:
        two.example.com:
        three.example.com: